global.psys = part_system_create_layer("Bullets", false);
global.p1 = part_type_create();
part_type_shape(global.p1, pt_shape_pixel);
part_type_size(global.p1, 1, 1.2, 0.01, 0);
part_type_scale(global.p1, 1, 1);
part_type_colour1(global.p1, c_gray);
part_type_alpha2(global.p1, 1, 0);
part_type_speed(global.p1, 0, 0, 0, 0);
part_type_direction(global.p1, 0, 180, 0, 0);
part_type_gravity(global.p1, 0, 270);
part_type_orientation(global.p1, 0, 0, 0, 0, 1);
part_type_blend(global.p1, 1);
part_type_life(global.p1, 15, 60);
